name: my_books_to_read
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^9.3.0+1
  dio: ^5.8.0+1
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  get_it: ^8.0.3
  provider: ^6.1.2
  shared_preferences: ^2.5.2

dev_dependencies:
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
